version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      gha:
        patterns: ["*"]
    open-pull-requests-limit: 5

  - package-ecosystem: bun
    directory: /
    schedule:
      interval: weekly
    groups:
      backend:
        patterns: ["*"]
    open-pull-requests-limit: 5

  - package-ecosystem: bun
    directory: /frontend
    schedule:
      interval: weekly
    groups:
      frontend:
        patterns: ["*"]
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
